version: '3.8'
networks:
  db-network:
volumes:
  db-vol:
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - db-network
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: projectdb
    healthcheck:
      test: [ "CMD","mysqladmin","ping",'-u','root','-ppassword' ]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5
  web-app:
    image: web-app-db
    restart: on-failure
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - 8080:8080
    networks:
      db-network:
    depends_on:
      db:
        condition: service_healthy